version: "3.3"
services:
  rpc:
    depends_on:
      - db
    build:
      context: .
      dockerfile: rpc.Dockerfile
    ports:
      - "$RPC_PORT:8080"
    env_file:
      - .env

  dispatcher:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dispatcher.Dockerfile
    env_file:
      - .env
