version: "3.3"
services:

  db:
    image: postgres
    volumes:
      - /home/pierce/.tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subs

  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: http_api.Dockerfile
    ports:
      - "$PORT:8080"
    env_file:
      - .env

  dispatcher:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dispatcher.Dockerfile
    env_file:
      - .env
