version: "3.3"
services:
  rpc:
    build:
      context: .
      dockerfile: rpc.Dockerfile
    ports:
      - "$RPC_PORT:8080"
    volumes:
      - "$JWT_PUBLIC_KEY_FILE:/jwt.key.pub"
    env_file:
      - .env

  dispatcher:
    build:
      context: .
      dockerfile: dispatcher.Dockerfile
    env_file:
      - .env
