// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubscriptionApiClient is the client API for SubscriptionApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionApiClient interface {
	Subscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Subscription, error)
}

type subscriptionApiClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionApiClient(cc grpc.ClientConnInterface) SubscriptionApiClient {
	return &subscriptionApiClient{cc}
}

func (c *subscriptionApiClient) Subscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Subscription, error) {
	out := new(Subscription)
	err := c.cc.Invoke(ctx, "/subscription_api/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionApiServer is the server API for SubscriptionApi service.
// All implementations must embed UnimplementedSubscriptionApiServer
// for forward compatibility
type SubscriptionApiServer interface {
	Subscribe(context.Context, *Subscription) (*Subscription, error)
	mustEmbedUnimplementedSubscriptionApiServer()
}

// UnimplementedSubscriptionApiServer must be embedded to have forward compatible implementations.
type UnimplementedSubscriptionApiServer struct {
}

func (UnimplementedSubscriptionApiServer) Subscribe(context.Context, *Subscription) (*Subscription, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSubscriptionApiServer) mustEmbedUnimplementedSubscriptionApiServer() {}

// UnsafeSubscriptionApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionApiServer will
// result in compilation errors.
type UnsafeSubscriptionApiServer interface {
	mustEmbedUnimplementedSubscriptionApiServer()
}

func RegisterSubscriptionApiServer(s grpc.ServiceRegistrar, srv SubscriptionApiServer) {
	s.RegisterService(&SubscriptionApi_ServiceDesc, srv)
}

func _SubscriptionApi_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionApiServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subscription_api/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionApiServer).Subscribe(ctx, req.(*Subscription))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionApi_ServiceDesc is the grpc.ServiceDesc for SubscriptionApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscription_api",
	HandlerType: (*SubscriptionApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _SubscriptionApi_Subscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sub_api.proto",
}
